apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "course-app.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "course-app.labels" . | nindent 4 }}
data:
  APP_MESSAGE: {{ .Values.app.message | quote }}
  APP_STORE: {{ .Values.app.store | quote }}
  APP_REDIS_URL: {{ .Values.app.redisUrl | quote }}
